scripts/config/templates/nginx.conf.erb
So that when nginx does redirects (when adding a trailing slash), it doesn't do it with the internal port specified.
=> Don't pass port in redirects

scripts/config/templates/nginx.conf.erb
See http://nginx.org/en/docs/http/ngx_http_gzip_module.html#gzip_types
=> MIME type "text/html" is already included by default

README.md, scripts/config/lib/nginx_config.rb, scripts/config/lib/nginx_config_util.rb, spec/scripts/config/lib/nginx_config_util_spec.rb, spec/simple_spec.rb
It's common to want to be able to test the frontend against various backends. The `origin` key supports _enviroment_ variable substitution using `${ENV_VAR_NAME}`. For instance, if there was a staging and production Heroku app for your API, you could setup the config above like the following:
```json
{
"proxies": {
"/api/": {
"origin": "https://${API_APP_NAME}.herokuapp.com/"
}
}
}
```
Then using the [config vars](https://devcenter.heroku.com/articles/config-vars), you can point the frontend app to the appropriate backend. To match the original proxy setup:
```bash
$ heroku config:set API_APP_NAME="hone-ember-todo-rails"
```
=> ability to use env vars in proxies origin with `${}`

scripts/config/templates/nginx.conf.erb
This fixes https://github.com/hone/heroku-buildpack-static/issues/31
Note that this is currently on top of https://github.com/hone/heroku-buildpack-static/pull/30, but that isn't required.
=> Enable the `proxy_ssl_server_name` option

README.md
I struggled with deploying a single page app that also needed to serve asset files, so I added some documentation which clarifies how route ordering works in this scenario.
=> Docs: clarify route ordering when serving single page apps

scripts/config/templates/nginx.conf.erb
This is basically the same fix as #32, which missed the proxy_ssl_server_name option for the fallback proxy location, so requests to the backend secured via ssl with sni failed.
PS: I dont really get why any request would hit the fallback proxy location. It would be great if somebody could point that out to me 😉
=> proxy_ssl_server_name on on fallback proxy

scripts/config/lib/nginx_config.rb, scripts/config/templates/nginx.conf.erb, spec/simple_spec.rb
Normally, when receiving a `Location` header, nginx will rewrite it to reference a URL if it matches the `proxy_pass`. This breaks when the scheme changes, since `proxy_pass` can have a scheme. For instance, if you have a proxy: "https://www.foo.com", but the `Location` on a redirect from that site returns "http://www.foo.com" nginx won't rewrite the URL. This fixes it by specifying the redirect for both http and https.
=> handle proxy redirects even if the scheme doesn't match

scripts/config/lib/nginx_config.rb, scripts/config/lib/nginx_config_util.rb, scripts/config/templates/nginx.conf.erb, spec/simple_spec.rb
Fixes #44 
https://tenzer.dk/nginx-with-dynamic-upstreams/
Nginx currently does not resolve domains passed to `proxy_pass`. By using a variable it works around the issue. The resolver is set to what's in `/etc/resolv.conf` and failing that `8.8.8.8` which is a Google DNS.
This also fixes a bug where fallback proxy match would just match the first proxy vs the longest.
=> Fixes #44. Respect DNS TTL for proxies.

README.md, scripts/config/templates/nginx.conf.erb, spec/fixtures/redirects_https_only/public_html/index.html, spec/fixtures/redirects_https_only/static.json, spec/simple_spec.rb
Fixes #64.
Remove the `proxies` section since it was overriding the `if` block.
=> https_only happens over proxies

bin/compile
I need to use few features that not yet merged to master So I fork this buildpack, merge required changes and have following config on heroku:
```
$ heroku buildpacks
=== my-app Buildpack URLs
1. https://codon-buildpacks.s3.amazonaws.com/buildpacks/heroku/emberjs.tgz
2. https://github.com/budnik/heroku-buildpack-static.git
```
As [emberjs](https://github.com/heroku/heroku-buildpack-emberjs) includes `static` buildpack in my setup I'm running this buildpack twice.
`nginx.conf.erb` from latter version of `heroku-buildpack-static` overrides former one, w/o affecting binaries.
two different `nginx.conf.erb` is created:
`~/bin/config/templates/nginx.conf.erb`
`~/bin/config/config/templates/nginx.conf.erb`
I have explanation why that is happening in commit message.
=> Makes config copying idempotent

README.md, scripts/config/lib/nginx_config.rb, scripts/config/templates/nginx.conf.erb
Add support for canonical host (e.g for SEO purpose)
I was inspired by https://github.com/keepworks/heroku-buildpack-static but simplify the nginx config.
Resolve #60 #110 #135
=> Add support for canonical host

CHANGELOG.md
And clean up the existing changelog slightly.
Entries derived from:
https://github.com/heroku/heroku-buildpack-static/compare/v3...v4
Closes #175.
=> Add missing changelog entries for v4

CHANGELOG.md, bin/compile
In order to reduce the size of the Heroku-20 support PR, I've split out some of the compile fixes/cleanup.
The most notable of these are:
- The build now fails early for unsupported stacks, rather than appearing to succeed only for the app to fail at runtime (as seen in #166)
- The printing of the nginx version is now fixed (#174)
See the individual commit messages (and changelog entries) for more details.
Refs [W-8367040](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008VTdWIAW/view).
=> Buildpack compile fixes and refactoring

CHANGELOG.md, buildpack.toml
Since currently the archive on the buildpack registry contains a lot more than the ~15 files needed at compile time:
```
$ curl -sSf https://buildpack-registry.s3.amazonaws.com/buildpacks/heroku-community/static.tgz | tar -zt | wc -l
234
```
See:
https://devcenter.heroku.com/articles/buildpack-registry#creating-a-buildpack-descriptor
Refs [W-8367040](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008VTdWIAW/view).
=> Exclude unnecessary files when publishing the buildpack

CHANGELOG.md, scripts/config/templates/nginx.conf.erb
The `mruby_post_read_handler` directive should always have been outside the `location` block, however due to a bug in ngx_mruby the previous implementation happened to still work.
In ngx_mruby 1.18.4 this silently stopped being the case:
https://github.com/matsumotory/ngx_mruby/issues/210
And in ngx_mruby 1.18.5 this incorrect usage was turned into an error:
https://github.com/matsumotory/ngx_mruby/pull/217
Moving `mruby_post_read_handler` outside the location block is a no-op for the older ngx_mruby currently used by this buildpack, but ensures compatibility with the newer ngx_mruby being used in the upcoming Heroku-20 support PR.
See matsumotory/ngx_mruby#210.
Refs [W-8367040](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008VTdWIAW/view).
=> Fix compatibility with ngx_mruby 1.18.4+

.gitignore, CHANGELOG.md, Makefile, README.md, bin/compile, scripts/build_ngx_mruby.sh
This adds support for the new Heroku-20 stack:
https://devcenter.heroku.com/articles/heroku-20-stack
The buildpack's binaries were previously generated by:
https://github.com/hone/docker-nginx-builder
However that repository is quite out of date, and much of its complexity is no longer required thanks to improvements to `ngx_mruby`'s upstream build scripts/process:
https://github.com/matsumotory/ngx_mruby/tree/v2.2.3/docs/install
https://github.com/matsumotory/ngx_mruby/blob/v2.2.3/build.sh
The new build script has been co-located in this buildpack to improve discoverability, and prevent needing to open PRs against multiple repos when performing updates.
The buildpack previously used a subdirectory of the Ruby buildpack's S3 bucket, however I've created a new S3 bucket to improve …
=> Add support for Heroku-20

CHANGELOG.md, scripts/build_ngx_mruby.sh
Previously the compile silently skipped the SSL module:
```
Configuration summary
...
+ OpenSSL library is not used
```
Which causes failures if SSL related directives are used.
Now the `--with-http_ssl_module` flag is passed, which results in:
```
Configuration summary
...
+ using system OpenSSL library
```
And `nginx -V` now includes an additional line:
```
built with OpenSSL 1.1.1f  31 Mar 2020
```
See:
https://github.com/matsumotory/ngx_mruby/tree/master/docs/install#3-a-using-buildsh
Fixes #185.
Closes [W-8449334](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008jEO5IAM/view).
=> Ensure the SSL module is enabled

CHANGELOG.md, bin/compile
Upgrades nginx from 1.9.7 to 1.19.0, to match that already used for Heroku-20. 
In addition, the buildpack now uses the correct binaries for these stacks, rather than using a binary compiled for Cedar-14.
The binaries were previously uploaded in https://github.com/heroku/heroku-buildpack-static/pull/186#issuecomment-730656605.
Fixes #165.
=> Update nginx for Heroku-16 and Heroku-18 to 1.19.0

README.md
Since this buildpack exists on the buildpack registry under the name `heroku-community/static`, and using buildpack registry versions is recommended over the GitHub URLs.
=> Docs: Use the buildpack registry URL in usage example

CHANGELOG.md, bin/detect
The error message is now output to `stderr` otherwise it's not shown.
Closes GUS-W-8799430.
Refs #198.
=> Output a helpful error message when no static.json is found

README.md
This PR corrects misspellings identified by the [check-spelling action](https://github.com/marketplace/actions/check-spelling).
The misspellings have been reported at https://github.com/jsoref/heroku-buildpack-static/commit/011cf1cff147b5d0ae17414af6261f9bf4aacf0c#commitcomment-51258705
The action reports that the changes in this PR would make it happy: https://github.com/jsoref/heroku-buildpack-static/commit/ce915a4cea53f3a46b930ac8117089645c9b280a
=> README: Fix spelling of 'instead'

.github/workflows/check_changelog.yml
eg:
https://github.com/heroku/heroku-buildpack-python/blob/5d6776f77a89e7ef3ada701d05c473117ecf817a/.github/workflows/check_changelog.yml
Notably, one can now use both a label and a PR description attribute, rather than the unsightly PR title annotation.
=> Port Check Changelog improvements from other repos

CHANGELOG.md, Makefile, bin/compile
Since they are EOL and it's no longer possible to perform builds using them.
Closes #214.
GUS-W-10346704.
=> Drop support for Cedar-14 and Heroku-16

CHANGELOG.md, bin/compile, scripts/build_ngx_mruby.sh
The binary build process for this buildpack uses the default `nginx` version specified by `ngx_mruby`. As such, updating `ngx_mruby` from `2.2.3` to `2.2.4` means the bundled `nginx` version is also updated from `1.19.0` to `1.21.3`:
https://github.com/matsumotory/ngx_mruby/blob/v2.2.3/nginx_version
https://github.com/matsumotory/ngx_mruby/blob/v2.2.4/nginx_version
Changes:
https://github.com/matsumotory/ngx_mruby/releases/tag/v2.2.4
https://nginx.org/en/CHANGES
GUS-W-10346704.
=> Update ngx_mruby to 2.2.4 and nginx to 1.21.3
